/* Material You — the wallpaper's palette, wearing Crimson & Paper's structure.
 *
 * On Android 12 and up the OS derives a set of tonal ramps from the user's
 * wallpaper. DynamicColorPlugin.java hands them across the Capacitor bridge;
 * this file turns them into the same token names index.css already defines,
 * and injects them as a stylesheet that outranks the static ones. Nothing else
 * in the app knows this exists — every component was already reading tokens,
 * so re-hueing the whole interface is one <style> element.
 *
 * WHAT IT DOES NOT DO: layout, spacing, radii, type and motion are untouched.
 * This is a colour pass. The point is that the app looks like it belongs on
 * *this* phone, not that it looks like someone else's Material app.
 *
 * WHERE IT DOES NOT RUN: a browser, the plain PWA, Android 11 and below, and
 * an older APK whose native half predates the plugin. All four keep the flag
 * crimson, which stays the app's real identity and its only face on the web.
 *
 * ── Why the shades are chosen and not hardcoded ────────────────────────────
 *
 * The obvious implementation aliases each role to a fixed shade (accent1_600
 * for the accent, and so on) the way the Material docs tabulate it, and on a
 * spec-correct palette that is provably safe: HCT's tone *is* CIELAB L*, WCAG
 * relative luminance *is* CIE Y, and L* determines Y — so the contrast between
 * two shades is fixed by their numbers alone and does not move with the
 * wallpaper's hue at all. Tone 40 on white is 6.46:1 whether the wallpaper is
 * blue or yellow.
 *
 * The catch is the word "spec-correct". Android's system_* resources are only
 * generated by AOSP's HCT solver on a phone running something close to AOSP.
 * Samsung, Xiaomi and others substitute their own palette extraction, and are
 * under no obligation to make shade N land on tone (1000 - N) / 10 — this app
 * is developed on a Samsung, so that is the common case here, not the exotic
 * one. A ramp whose numbers no longer mean what they say turns the tabulated
 * mapping into unreadable text, silently, on someone else's wallpaper.
 *
 * So every role below is a *candidate list* walked in order until one measures
 * up, against the same floors index.css documents: 7:1 for body text, 4.5:1
 * for muted text, 3:1 for anything that is a control's edge. The lists are
 * ordered from the shade the M3 table would pick toward the safer end of the
 * ramp, so on a well-behaved palette the first candidate always wins and this
 * costs nothing; on a rogue one it degrades toward readable instead of toward
 * broken. The expected winner's exact ratio is noted per token, in the same
 * form as index.css's own annotations.
 *
 * ── Android's shade numbers vs Material's tone numbers ─────────────────────
 *
 * They run opposite ways. Android's shade 0 is white and shade 1000 is black;
 * Material's tone 0 is black and tone 100 is white. Shade N is about tone
 * (1000 - N) / 10. This file speaks shades throughout, because that is what
 * the resource names on the other side of the bridge say.
 */
import { Capacitor, registerPlugin } from '@capacitor/core'

/** shade number -> "#RRGGBB", as handed over by DynamicColorPlugin. */
type Ramp = Record<string, string>

/* accent2 is deliberately absent. The OS derives it, but nothing here maps to
 * it: M3 spends it on secondary containers, and this app has one accent, one
 * companion hue (accent3, the wordmark) and two neutral ramps. Adding it to
 * the bridge payload to leave it unused would only invite someone to reach for
 * it without a role in mind. */
interface Palette {
  accent1: Ramp
  accent3: Ramp
  neutral1: Ramp
  neutral2: Ramp
}

interface DynamicColorPlugin {
  getPalette(): Promise<{ available: boolean; palette?: Palette }>
}

const DynamicColor = registerPlugin<DynamicColorPlugin>('DynamicColor')

const PREF_KEY = 'lekh:dynamic-color'
/* The generated CSS, cached so a relaunch paints in the right colours on the
 * first frame instead of flashing crimson while the bridge call round-trips.
 * The suffix is a schema version: bump it whenever the token mapping below
 * changes, or returning users keep last version's stylesheet forever. */
const CSS_CACHE_KEY = 'lekh:dynamic-color-css:1'
const STYLE_ID = 'dynamic-color'
const ROOT_ATTR = 'data-dynamic-color'

/* ── contrast ─────────────────────────────────────────────────────────────
 * WCAG 2.1 relative luminance. The same arithmetic that produced the ratios
 * annotated in index.css, so the two palettes are held to one standard. */

function channel(value: number): number {
  const c = value / 255
  return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
}

function luminance(hex: string): number {
  const n = parseInt(hex.slice(1), 16)
  return (
    0.2126 * channel((n >> 16) & 255) +
    0.7152 * channel((n >> 8) & 255) +
    0.0722 * channel(n & 255)
  )
}

function contrast(a: string, b: string): number {
  const [x, y] = [luminance(a), luminance(b)]
  return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05)
}

/**
 * The first shade in `shades` that clears `min` against every background in
 * `against`, or the last one if none do.
 *
 * Falling back to the last candidate rather than throwing is deliberate, and
 * it is the OEM case this whole approach exists for: the lists below are
 * ordered toward the extreme end of each ramp (darkest on light, lightest on
 * dark), so the last candidate is always the most readable shade the palette
 * offers for that role. On a ramp whose numbers do mean what they say, this
 * never fires — the first candidate wins every time. On one where they do not,
 * "as readable as this palette gets" is the right way to lose.
 *
 * A shade being absent is not handled here: isComplete() rejects a partial
 * palette before any of this runs, so the skip below is belt-and-braces.
 */
function pick(ramp: Ramp, shades: number[], min: number, ...against: string[]): string {
  let last = ''
  for (const shade of shades) {
    const hex = ramp[String(shade)]
    if (!hex) continue
    last = hex
    if (against.every((bg) => contrast(hex, bg) >= min)) return hex
  }
  return last
}

/** A shade that must exist — guaranteed by isComplete() before any of this runs. */
function at(ramp: Ramp, shade: number): string {
  return ramp[String(shade)]
}

/* Every shade the mapping can reach, checked up front rather than per lookup.
 * A missing one is not a contrast problem, it is `--surface: undefined` in the
 * emitted CSS — a declaration the browser drops, leaving that single token on
 * its static value while everything around it moved. Half a palette is a far
 * worse outcome than none, so a ramp with a hole in it is refused whole. */
const REQUIRED = [0, 10, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

function isComplete(palette: Palette | undefined): palette is Palette {
  if (!palette) return false
  return (['accent1', 'accent3', 'neutral1', 'neutral2'] as const).every((family) => {
    const ramp = palette[family]
    return !!ramp && REQUIRED.every((shade) => /^#[0-9a-fA-F]{6}$/.test(ramp[String(shade)] ?? ''))
  })
}

function alpha(hex: string, percent: number): string {
  return `color-mix(in srgb, ${hex} ${percent}%, transparent)`
}

/* ── the mapping ───────────────────────────────────────────────────────── */

/* Every token index.css's two dark selectors switch, and nothing else. The
 * palette is only allowed to change colours that already vary between light
 * and dark — spacing, radii, type and motion tokens are not in this set and
 * never get emitted, so there is no way for a colour pass to move the layout.
 *
 * --ok / --warn / --danger are deliberately absent: green means saved and red
 * means wrong, and neither survives being repainted by a wallpaper. */
function lightTokens(p: Palette): Record<string, string> {
  const bg = at(p.neutral1, 10)
  const surface = at(p.neutral1, 0)
  const surface2 = at(p.neutral2, 50)
  const accentBg = at(p.accent1, 100)

  /* The accent is a *fill* — it carries --on-accent as words — so it is picked
     against white rather than against the page, and then checked against the
     page for the 3:1 UI-component floor. This is the split index.css insists
     on keeping: --accent fills, --accent-text is for type. */
  const accent = pickFill(p.accent1, [600, 700, 800], bg)
  const accentText = pick(p.accent1, [700, 800, 900], 4.5, bg, accentBg)

  /* Ratios are the spec-correct palette's, computed from tone: the surfaces
     are tones 99/100/95 and each text shade's tone is (1000 - shade) / 10.
     They are what the first candidate in each list scores; a rogue OEM ramp
     falls through to the next one. */
  return {
    '--bg': bg,
    '--surface': surface,
    '--surface-2': surface2,
    '--code-bg': surface2,
    /* Not M3's onSurface (tone 10) — that is --text-h here. Splitting body
       text off at tone 30 is what keeps the three-level hierarchy the static
       palette has (16.98 / 7.61 / 5.05) instead of collapsing headings and
       body into one colour the way the raw M3 role table does. */
    '--text': pick(p.neutral1, [700, 800, 900], 7, bg, surface), // 9.12 on bg
    '--text-h': pick(p.neutral1, [900, 1000], 7, bg, surface), // 16.72 on bg
    '--muted': pick(p.neutral2, [600, 700, 800], 4.5, bg, surface, surface2), // 5.70 on surface-2, the tightest pair here
    '--border': at(p.neutral2, 100), // 1.26 on bg — decorative, and that is all it has to be
    /* Starts a shade softer than it will end up: tone 70 measures 2.30 on
       white and fails the 3:1 UI floor, so this lands on tone 60 at 3.17.
       Left in the list rather than deleted because a palette whose tone 70
       does clear 3:1 should get the softer edge. */
    '--border-field': pick(p.neutral2, [300, 400, 500, 600], 3, surface),
    '--accent': accent, // tone 40: 6.46 on white, 6.30 on bg
    '--accent-text': accentText, // 9.12 on bg, 7.24 on --accent-bg
    '--on-accent': '#FFFFFF',
    '--accent-bg': accentBg,
    '--accent-border': alpha(accent, 40),
    /* The ख of the wordmark. It was the flag's blue — never a control, never a
       link, just the one place a second colour appears. accent3 is M3's
       tertiary: the role that exists for exactly this, a companion hue that is
       not competing to be the primary action. Held to the same 7:1 the flag
       blue met, because it is display type. */
    '--flag-blue': pick(p.accent3, [700, 800, 900], 7, bg), // 9.12 on bg
    '--shadow-accent': `0 2px 8px -2px ${alpha(accent, 40)}`,
    '--bar-bg': alpha(bg, 82),
  }
}

function darkTokens(p: Palette): Record<string, string> {
  const bg = at(p.neutral1, 900)
  const surface = at(p.neutral1, 800)
  const surface2 = at(p.neutral2, 700)

  /* Not the light mode's shade, for the reason index.css spells out about
     #C8102E: a tone-40 accent on a tone-10 background is around 1.6:1. The
     dark accent comes off the light end of the ramp and takes a dark
     --on-accent, inverting the pair. */
  const accent = pick(p.accent1, [200, 100, 50], 3, bg, surface)

  /* The dark ramp is tones 10 / 20 / 30, which is as tight as Android's
     neutral shades allow — there is nothing between shade 900 and 800. That
     tone-30 panel is what sets the text ladder below: it is a lighter
     background than the page, so in dark mode it, not --bg, is the binding
     constraint for anything written on it. (In light mode the page is the
     binding one. Both are passed to every pick either way, rather than
     reasoning about which is tighter token by token.)

     Which is why this half follows M3's own dark roles — onSurface at tone 90,
     onSurfaceVariant at tone 80 — instead of the wider split the light half
     inherits from the static palette. Tone 70 muted text is the prettier
     choice and it measures 4.07 on a tone-30 panel: under the floor, in the
     cheat-sheet panel and the calendar, which are exactly the two places
     --muted sits on --surface-2. Going to tone 80 fixes it, and then body text
     has to move up to tone 90 or the two become the same colour. */
  return {
    '--bg': bg,
    '--surface': surface,
    '--surface-2': surface2,
    '--code-bg': surface2,
    '--text': pick(p.neutral1, [100, 50], 7, bg, surface), // 13.27 on bg, 10.18 on surface
    '--text-h': pick(p.neutral1, [50, 0], 7, bg, surface), // 15.12 on bg, 11.59 on surface
    '--muted': pick(p.neutral2, [200, 100], 4.5, bg, surface, surface2), // 5.49 on surface-2, the tightest pair here
    '--border': surface2, // 1.41 on surface — decorative
    /* Tone 50 measures 2.93 on a tone-20 surface — a hair under the 3:1 UI
       floor — so this lands on tone 60 at 4.15. Kept in the list for the same
       reason as its light-mode counterpart. */
    '--border-field': pick(p.neutral2, [500, 400, 300], 3, surface),
    '--accent': accent, // tone 80: 10.07 on bg, 7.72 on surface
    /* One value for both, as the static dark palette also does: a dark accent
       is already light enough to be read as type. */
    '--accent-text': accent,
    '--on-accent': pick(p.accent1, [900, 1000], 4.5, accent), // 10.07 on --accent
    /* Tone 20, not the tone-30 M3 would use for a container. This token is a
       *wash* here — ::selection and the tinted button backgrounds sit under
       near-white type, and tone 30 starts fighting it. */
    '--accent-bg': at(p.accent1, 800), // 11.59 under --text-h
    '--accent-border': alpha(accent, 40),
    '--flag-blue': pick(p.accent3, [200, 100], 7, bg, surface), // 7.72 on surface
    '--shadow-accent': `0 2px 8px -2px ${alpha(accent, 35)}`,
    '--bar-bg': alpha(bg, 82),
  }
}

/**
 * --accent is the one token picked against two things at once, so it gets its
 * own function rather than a fourth argument on pick(): it must carry white
 * type at 4.5:1 (it is a button with a label on it) *and* clear 3:1 against
 * the page (it is also a UI shape — the caret, the active tab underline).
 * Walking toward the dark end of the ramp raises both at once, which is why a
 * single ordered list can satisfy both.
 */
function pickFill(ramp: Ramp, shades: number[], bg: string): string {
  let last = ''
  for (const shade of shades) {
    const hex = ramp[String(shade)]
    if (!hex) continue
    last = hex
    if (contrast(hex, '#FFFFFF') >= 4.5 && contrast(hex, bg) >= 3) return hex
  }
  return last
}

function declarations(tokens: Record<string, string>): string {
  return Object.entries(tokens)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n')
}

/**
 * The stylesheet, in the same three-selector shape index.css uses.
 *
 * Specificity settles all of it, with nothing resting on source order — worth
 * stating, because "append the stylesheet last" is a fragile thing to depend
 * on next to a bundler that reorders and re-injects CSS. index.css sets the
 * light tokens on `:root` (0,1,0) and the dark ones on `:root[data-theme=dark]`
 * and `:root:not([data-theme=light])` (both 0,2,0). Adding [data-dynamic-color]
 * lifts the light rule here to 0,2,0, which beats static light outright, and
 * the dark rules to 0,3,0, which beats every other rule that can match at the
 * same time — including this file's own light rule, which is what makes the
 * 0,2,0 tie against static dark harmless rather than a bug waiting on load
 * order. Removing the attribute from <html> drops the whole thing back to
 * Crimson & Paper with no cleanup.
 *
 * The two dark bodies are identical and generated from the same string, which
 * is the safeguard index.css asks for in prose — one of them living inside a
 * media query is the only difference between them, and a token that reached
 * one and not the other would only misbehave for users whose OS preference
 * disagrees with their saved choice.
 */
function buildCss(p: Palette): string {
  const light = declarations(lightTokens(p))
  const dark = declarations(darkTokens(p))
  return [
    `:root[${ROOT_ATTR}] {\n${light}\n}`,
    `@media (prefers-color-scheme: dark) {\n:root[${ROOT_ATTR}]:not([data-theme='light']) {\n${dark}\n}\n}`,
    `:root[${ROOT_ATTR}][data-theme='dark'] {\n${dark}\n}`,
  ].join('\n\n')
}

/* ── applying ─────────────────────────────────────────────────────────── */

function styleEl(): HTMLStyleElement {
  let el = document.getElementById(STYLE_ID) as HTMLStyleElement | null
  if (!el) {
    el = document.createElement('style')
    el.id = STYLE_ID
    /* Appended to <head>, after the bundle's own stylesheet — see buildCss on
       why source order is load-bearing for the light rule. */
    document.head.appendChild(el)
  }
  return el
}

function paint(css: string | null): void {
  if (css) {
    styleEl().textContent = css
    document.documentElement.setAttribute(ROOT_ATTR, '')
  } else {
    document.getElementById(STYLE_ID)?.remove()
    document.documentElement.removeAttribute(ROOT_ATTR)
  }
  /* The status bar tracks --bg, and --bg just moved. */
  syncThemeColor()
}

/**
 * Repoints the theme-color meta at whatever --bg currently computes to.
 *
 * Kept here rather than duplicated in theme.ts: reading the computed value is
 * the only version of this that cannot go stale, and it is the same answer
 * whether the palette is dynamic or static.
 */
export function syncThemeColor(): void {
  const bg = getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()
  if (bg) document.getElementById('theme-color')?.setAttribute('content', bg)
}

/* ── preference + state ───────────────────────────────────────────────── */

function prefEnabled(): boolean {
  try {
    /* Default on. Someone running the app on an Android 12+ phone gets the
       phone's colours without going looking for a setting; the switch in the
       About sheet exists to get the flag red back, not to opt in. */
    return localStorage.getItem(PREF_KEY) !== 'off'
  } catch {
    return true
  }
}

function cachedCss(): string | null {
  try {
    return localStorage.getItem(CSS_CACHE_KEY)
  } catch {
    return null
  }
}

export interface DynamicColorState {
  /** The palette is actually reachable: native app, Android 12+, plugin present. */
  supported: boolean
  enabled: boolean
}

let state: DynamicColorState = { supported: false, enabled: prefEnabled() }
const listeners = new Set<() => void>()

function setState(next: DynamicColorState): void {
  if (next.supported === state.supported && next.enabled === state.enabled) return
  state = next
  for (const fn of listeners) fn()
}

export function getDynamicColorState(): DynamicColorState {
  return state
}

export function subscribeDynamicColor(fn: () => void): () => void {
  listeners.add(fn)
  return () => listeners.delete(fn)
}

export function setDynamicColorEnabled(enabled: boolean): void {
  try {
    localStorage.setItem(PREF_KEY, enabled ? 'on' : 'off')
  } catch {
    // Applies this session regardless, it just won't be remembered.
  }
  setState({ ...state, enabled })
  paint(enabled ? cachedCss() : null)
}

/**
 * Synchronous, and called before React mounts.
 *
 * The bridge call is a round trip, and a round trip after first paint is a
 * visible crimson-to-wallpaper flip on every launch. Repainting last launch's
 * stylesheet immediately and correcting it a beat later means the flip only
 * ever happens on the first launch after the wallpaper changes — where it is
 * the correct thing to show anyway.
 */
export function bootDynamicColor(): void {
  if (!prefEnabled()) return
  const css = cachedCss()
  if (css) paint(css)
}

/**
 * Asks the OS for the current palette and reconciles everything with it.
 *
 * Safe to call anywhere: on the web, on an old phone, or inside an APK built
 * before the plugin existed, isPluginAvailable is false and this is a no-op
 * that leaves the static palette alone. The cache is cleared in that case too,
 * so a phone that stops reporting a palette does not keep painting a stale one.
 */
export async function refreshDynamicColor(): Promise<void> {
  if (!Capacitor.isNativePlatform() || !Capacitor.isPluginAvailable('DynamicColor')) {
    return
  }

  let palette: Palette | undefined
  try {
    const result = await DynamicColor.getPalette()
    if (result.available) palette = result.palette
  } catch {
    // Pre-Android-12, or the lookup came back empty. Static palette stands.
  }

  if (!isComplete(palette)) {
    try {
      localStorage.removeItem(CSS_CACHE_KEY)
    } catch {
      // Nothing to do; paint(null) below still drops it for this session.
    }
    setState({ supported: false, enabled: state.enabled })
    paint(null)
    return
  }

  const css = buildCss(palette)
  try {
    localStorage.setItem(CSS_CACHE_KEY, css)
  } catch {
    // Quota or private mode — costs a flash next launch, nothing more.
  }
  setState({ supported: true, enabled: state.enabled })
  paint(state.enabled ? css : null)
}
