export const BODY: Record<string, string> = {
  tauko: 'टाउको',
  ankha: 'आँखा',
  aankha: 'आँखा',
  kan: 'कान',
  kaan: 'कान',
  nak: 'नाक',
  naak: 'नाक',
  mukh: 'मुख',
  oth: 'ओठ',
  hat: 'हात',
  haat: 'हात',
  khutta: 'खुट्टा',
  pet: 'पेट',
  kapal: 'कपाल',
  dant: 'दाँत',
  daat: 'दाँत',
  jibro: 'जिब्रो',
  mutu: 'मुटु',
  ragat: 'रगत',
  chhala: 'छाला',
  ghati: 'घाँटी',
  aula: 'औँला',
}
