// English words as Nepali writes them. People text in romanized Nepali with
// English mixed straight in ("school jaane", "facebook ma post gara"), and the
// pattern spells an English word letter by letter: school → स्चूल, college →
// कोल्लेगे, police → पोलिके. These are the common ones in the spelling Nepali
// uses for them — transliterated, not translated (police → पुलिस, not प्रहरी).
//
// Left out on purpose: English words whose spelling is also how someone would
// type a Nepali word (bat → बाट "from", sir → शिर "head", job → जब "when",
// hi, no, to, man), because a dictionary hit beats the pattern and would take
// the Nepali word away from the person who meant it.
export const ENGLISH: Record<string, string> = {
  // phone and internet
  facebook: 'फेसबुक',
  youtube: 'युट्युब',
  tiktok: 'टिकटक',
  instagram: 'इन्स्टाग्राम',
  whatsapp: 'ह्वाट्सएप',
  viber: 'भाइबर',
  messenger: 'मेसेन्जर',
  google: 'गुगल',
  wifi: 'वाइफाइ',
  online: 'अनलाइन',
  offline: 'अफलाइन',
  video: 'भिडियो',
  selfie: 'सेल्फी',
  laptop: 'ल्यापटप',
  charger: 'चार्जर',
  charge: 'चार्ज',
  battery: 'ब्याट्री',
  sim: 'सिम',
  recharge: 'रिचार्ज',
  message: 'म्यासेज',
  msg: 'म्यासेज',
  email: 'इमेल',
  password: 'पासवर्ड',
  account: 'एकाउन्ट',
  app: 'एप',
  website: 'वेबसाइट',
  link: 'लिङ्क',
  post: 'पोस्ट',
  share: 'सेयर',
  like: 'लाइक',
  comment: 'कमेन्ट',
  status: 'स्टाटस',
  call: 'कल',
  missed: 'मिस्ड',
  number: 'नम्बर',
  // school and work
  school: 'स्कुल',
  college: 'कलेज',
  campus: 'क्याम्पस',
  university: 'युनिभर्सिटी',
  class: 'क्लास',
  teacher: 'टिचर',
  madam: 'म्याडम',
  exam: 'एक्जाम',
  result: 'रिजल्ट',
  form: 'फारम',
  tuition: 'ट्युसन',
  office: 'अफिस',
  company: 'कम्पनी',
  meeting: 'मिटिङ',
  bank: 'बैंक',
  atm: 'एटिएम',
  card: 'कार्ड',
  cash: 'क्यास',
  bill: 'बिल',
  // health and help
  doctor: 'डाक्टर',
  hospital: 'अस्पताल',
  clinic: 'क्लिनिक',
  nurse: 'नर्स',
  ambulance: 'एम्बुलेन्स',
  police: 'पुलिस',
  // getting around and staying
  bus: 'बस',
  taxi: 'ट्याक्सी',
  car: 'कार',
  bike: 'बाइक',
  scooter: 'स्कुटर',
  ticket: 'टिकट',
  airport: 'एयरपोर्ट',
  restaurant: 'रेस्टुरेन्ट',
  room: 'रुम',
  // everyday talk
  sorry: 'सरी',
  thanks: 'थ्याङ्क्स',
  thank: 'थ्याङ्क',
  please: 'प्लिज',
  ok: 'ओके',
  okay: 'ओके',
  hello: 'हेलो',
  bye: 'बाइ',
  birthday: 'बर्थडे',
  party: 'पार्टी',
  happy: 'ह्याप्पी',
  love: 'लभ',
  tv: 'टिभी',
  football: 'फुटबल',
  cricket: 'क्रिकेट',
  match: 'म्याच',
  team: 'टिम',
  time: 'टाइम',
  minute: 'मिनेट',
  second: 'सेकेन्ड',
}
