// Nature and animals.
export const NATURE: Record<string, string> = {
  surya: 'सूर्य',
  gham: 'घाम',
  ghaam: 'घाम',
  jun: 'जुन',
  chandrama: 'चन्द्रमा',
  akash: 'आकाश',
  aakash: 'आकाश',
  hawa: 'हावा',
  hava: 'हावा',
  badal: 'बादल',
  baadal: 'बादल',
  hiu: 'हिउँ',
  hiun: 'हिउँ',
  aago: 'आगो',
  rukh: 'रूख',
  phul: 'फूल',
  ful: 'फूल',
  maato: 'माटो',
  mato: 'माटो',
  dhunga: 'ढुङ्गा',
  samudra: 'समुद्र',
  prakriti: 'प्रकृति',
  chara: 'चरा',
  kukur: 'कुकुर',
  biralo: 'बिरालो',
  gai: 'गाई',
  bhaisi: 'भैंसी',
  bhainsi: 'भैंसी',
  bakhra: 'बाख्रा',
  hatti: 'हात्ती',
}
