// Number words (digit strings are handled by the DIGITS map, not the dict).
export const NUMBERS: Record<string, string> = {
  ek: 'एक',
  dui: 'दुई',
  tin: 'तीन',
  char: 'चार',
  chaar: 'चार',
  panch: 'पाँच',
  paanch: 'पाँच',
  saat: 'सात',
  aath: 'आठ',
  nau: 'नौ',
  das: 'दस',
  bis: 'बीस',
  tis: 'तीस',
  chalis: 'चालीस',
  pachas: 'पचास',
  saya: 'सय',
  hajar: 'हजार',
  lakh: 'लाख',
  karod: 'करोड',
  adha: 'आधा',
  aadha: 'आधा',
  pahilo: 'पहिलो',
  dosro: 'दोस्रो',
  tesro: 'तेस्रो',
  chautho: 'चौथो',
}
