// The big one: common conjugations of हुनु and the most frequent verbs.
// chh/ch spelling alternates are listed as separate keys throughout.
export const VERBS: Record<string, string> = {
  // हुनु — to be
  ho: 'हो',
  hoina: 'होइन',
  hun: 'हुन्',
  hunu: 'हुनु',
  chu: 'छु',
  chhu: 'छु',
  cha: 'छ',
  chha: 'छ',
  chau: 'छौ',
  chhau: 'छौ',
  chin: 'छिन्',
  chhin: 'छिन्',
  chan: 'छन्',
  chhan: 'छन्',
  chaina: 'छैन',
  chhaina: 'छैन',
  huncha: 'हुन्छ',
  hunchha: 'हुन्छ',
  hudaina: 'हुँदैन',
  hundaina: 'हुँदैन',
  hunuhuncha: 'हुनुहुन्छ',
  hunuhunchha: 'हुनुहुन्छ',
  bhayo: 'भयो',
  bhaena: 'भएन',
  bhaeko: 'भएको',
  hune: 'हुने',
  hola: 'होला',
  thiyo: 'थियो',
  thie: 'थिए',
  thiena: 'थिएन',
  // गर्नु — to do
  garnu: 'गर्नु',
  garchu: 'गर्छु',
  garchhu: 'गर्छु',
  garcha: 'गर्छ',
  garchha: 'गर्छ',
  garchau: 'गर्छौ',
  garchhau: 'गर्छौ',
  garchan: 'गर्छन्',
  garchhan: 'गर्छन्',
  garnuhuncha: 'गर्नुहुन्छ',
  garnuhunchha: 'गर्नुहुन्छ',
  garyo: 'गर्यो',
  gare: 'गरे',
  gareko: 'गरेको',
  garera: 'गरेर',
  garna: 'गर्न',
  garne: 'गर्ने',
  garnus: 'गर्नुस्',
  garnuhos: 'गर्नुहोस्',
  gardai: 'गर्दै',
  // जानु — to go
  janu: 'जानु',
  janchu: 'जान्छु',
  janchhu: 'जान्छु',
  jancha: 'जान्छ',
  janchha: 'जान्छ',
  jane: 'जाने',
  jana: 'जान',
  gayo: 'गयो',
  gae: 'गए',
  gaeko: 'गएको',
  jau: 'जाऊ',
  janus: 'जानुस्',
  jandai: 'जाँदै',
  // आउनु — to come
  aunu: 'आउनु',
  auchu: 'आउँछु',
  auchhu: 'आउँछु',
  aucha: 'आउँछ',
  auchha: 'आउँछ',
  aune: 'आउने',
  aayo: 'आयो',
  ayo: 'आयो',
  aunus: 'आउनुस्',
  audai: 'आउँदै',
  // खानु — to eat
  khanu: 'खानु',
  khanchu: 'खान्छु',
  khanchhu: 'खान्छु',
  khancha: 'खान्छ',
  khanchha: 'खान्छ',
  khane: 'खाने',
  khayo: 'खायो',
  khaeko: 'खाएको',
  khanus: 'खानुस्',
  // दिनु — to give
  dinu: 'दिनु',
  dinchu: 'दिन्छु',
  dinchhu: 'दिन्छु',
  dincha: 'दिन्छ',
  dinchha: 'दिन्छ',
  dine: 'दिने',
  diyo: 'दियो',
  dieko: 'दिएको',
  dinus: 'दिनुस्',
  // लिनु — to take
  linu: 'लिनु',
  linchu: 'लिन्छु',
  linchhu: 'लिन्छु',
  lincha: 'लिन्छ',
  linchha: 'लिन्छ',
  line: 'लिने',
  liyo: 'लियो',
  linus: 'लिनुस्',
  // भन्नु — to say
  bhannu: 'भन्नु',
  bhanchu: 'भन्छु',
  bhanchhu: 'भन्छु',
  bhancha: 'भन्छ',
  bhanchha: 'भन्छ',
  bhanne: 'भन्ने',
  bhanyo: 'भन्यो',
  bhane: 'भने',
  bhaneko: 'भनेको',
  bhanera: 'भनेर',
  bhannus: 'भन्नुस्',
  // हेर्नु — to look
  hernu: 'हेर्नु',
  herchu: 'हेर्छु',
  herchhu: 'हेर्छु',
  hercha: 'हेर्छ',
  herchha: 'हेर्छ',
  herne: 'हेर्ने',
  heryo: 'हेर्यो',
  hereko: 'हेरेको',
  hernus: 'हेर्नुस्',
  herdai: 'हेर्दै',
  hera: 'हेर',
  // बस्नु — to sit / stay
  basnu: 'बस्नु',
  baschu: 'बस्छु',
  baschhu: 'बस्छु',
  bascha: 'बस्छ',
  baschha: 'बस्छ',
  basne: 'बस्ने',
  basyo: 'बस्यो',
  basnus: 'बस्नुस्',
  bas: 'बस',
  // पाउनु — to get
  paunu: 'पाउनु',
  paucha: 'पाउँछ',
  pauchha: 'पाउँछ',
  payo: 'पायो',
  paune: 'पाउने',
  paeko: 'पाएको',
  paincha: 'पाइन्छ',
  painchha: 'पाइन्छ',
  // सक्नु — can
  saknu: 'सक्नु',
  sakchu: 'सक्छु',
  sakchhu: 'सक्छु',
  sakcha: 'सक्छ',
  sakchha: 'सक्छ',
  sakdaina: 'सक्दैन',
  sakincha: 'सकिन्छ',
  sakinchha: 'सकिन्छ',
  sakyo: 'सक्यो',
  // पर्नु — must / to fall
  parnu: 'पर्नु',
  parcha: 'पर्छ',
  parchha: 'पर्छ',
  pardaina: 'पर्दैन',
  paryo: 'पर्यो',
  parne: 'पर्ने',
  // चाहनु — to want
  chahanchu: 'चाहन्छु',
  chahanchhu: 'चाहन्छु',
  chahancha: 'चाहन्छ',
  chahanchha: 'चाहन्छ',
  chahiyo: 'चाहियो',
  chahincha: 'चाहिन्छ',
  chahinchha: 'चाहिन्छ',
  // मनपर्नु — to like
  manparcha: 'मनपर्छ',
  manparchha: 'मनपर्छ',
  manpardaina: 'मनपर्दैन',
  manparyo: 'मनपर्यो',
  // खेल्नु — to play
  khelnu: 'खेल्नु',
  khelchu: 'खेल्छु',
  khelchhu: 'खेल्छु',
  khelne: 'खेल्ने',
  khelyo: 'खेल्यो',
  // सुत्नु — to sleep
  sutnu: 'सुत्नु',
  sutchu: 'सुत्छु',
  sutchhu: 'सुत्छु',
  sutne: 'सुत्ने',
  sutyo: 'सुत्यो',
  // उठ्नु — to get up
  uthnu: 'उठ्नु',
  uthne: 'उठ्ने',
  uthyo: 'उठ्यो',
  // पढ्नु — to read / study
  padhnu: 'पढ्नु',
  padhchu: 'पढ्छु',
  padhchhu: 'पढ्छु',
  padhne: 'पढ्ने',
  padheko: 'पढेको',
  padhyo: 'पढ्यो',
  // लेख्नु — to write
  lekhnu: 'लेख्नु',
  lekhchu: 'लेख्छु',
  lekhchhu: 'लेख्छु',
  lekhne: 'लेख्ने',
  lekheko: 'लेखेको',
  lekhyo: 'लेख्यो',
  // किन्नु — to buy
  kinnu: 'किन्नु',
  kinne: 'किन्ने',
  kinyo: 'किन्यो',
  // पिउनु — to drink
  piunu: 'पिउनु',
  piune: 'पिउने',
  piyo: 'पियो',
  // बुझ्नु — to understand
  bujhnu: 'बुझ्नु',
  bujhne: 'बुझ्ने',
  bujhyo: 'बुझ्यो',
  // सोच्नु — to think
  sochnu: 'सोच्नु',
  sochne: 'सोच्ने',
  socheko: 'सोचेको',
  sochyo: 'सोच्यो',
  // राख्नु — to keep / put
  rakhnu: 'राख्नु',
  rakhne: 'राख्ने',
  rakhyo: 'राख्यो',
  rakheko: 'राखेको',
  // मिल्नु — to match / get along
  milcha: 'मिल्छ',
  milchha: 'मिल्छ',
  milyo: 'मिल्यो',
  milne: 'मिल्ने',
  // लाग्नु — to feel / take (time)
  lagcha: 'लाग्छ',
  lagchha: 'लाग्छ',
  lagyo: 'लाग्यो',
  lagne: 'लाग्ने',
  // सिक्नु — to learn
  siknu: 'सिक्नु',
  sikne: 'सिक्ने',
  sikchu: 'सिक्छु',
  sikchhu: 'सिक्छु',
  sikeko: 'सिकेको',
  // ल्याउनु — to bring
  lyaunu: 'ल्याउनु',
  lyaune: 'ल्याउने',
  lyayo: 'ल्यायो',
  // पुग्नु — to arrive / suffice
  pugcha: 'पुग्छ',
  pugchha: 'पुग्छ',
  pugyo: 'पुग्यो',
  // बोल्नु — to speak
  bolnu: 'बोल्नु',
  bolne: 'बोल्ने',
  bolyo: 'बोल्यो',
  bolchu: 'बोल्छु',
  bolchhu: 'बोल्छु',
  // सोध्नु — to ask
  sodhnu: 'सोध्नु',
  sodhne: 'सोध्ने',
  sodhyo: 'सोध्यो',
}
