export { CONS, VOW, DIGITS, SIGNS } from './maps'
export { DICT } from './dict'
export { VARIANTS } from './variants'
export { phonetic } from './phonetic'
export { convert, convertPhrase } from './convert'
export { suggest } from './suggest'
