// Longest-match-first romanization tables. Keys are checked 3/2/1 chars long
// in phonetic.ts, so multi-char keys (chh, ksh, gy, sh, ...) must stay here
// even though single-char keys could theoretically compose them — greedy
// matching on the multi-char form is what makes "chha" -> छ + ा work.
export const CONS: Record<string, string> = {
  chh: 'छ',
  ksh: 'क्ष',
  gy: 'ज्ञ',
  kh: 'ख',
  gh: 'घ',
  ch: 'च',
  jh: 'झ',
  Th: 'ठ',
  Dh: 'ढ',
  th: 'थ',
  dh: 'ध',
  ph: 'फ',
  bh: 'भ',
  sh: 'श',
  Sh: 'ष',
  ng: 'ङ',
  ny: 'ञ',
  k: 'क',
  g: 'ग',
  c: 'च',
  j: 'ज',
  T: 'ट',
  D: 'ड',
  N: 'ण',
  t: 'त',
  d: 'द',
  n: 'न',
  p: 'प',
  f: 'फ',
  b: 'ब',
  m: 'म',
  y: 'य',
  r: 'र',
  l: 'ल',
  w: 'व',
  v: 'व',
  s: 'स',
  h: 'ह',
  x: 'क्ष',
  q: 'क',
  z: 'ज',
}

// [independent form, matra] — matra is appended after a preceding consonant,
// independent form is used word-initially / after another vowel.
export const VOW: Record<string, [string, string]> = {
  rri: ['ऋ', 'ृ'],
  aa: ['आ', 'ा'],
  ai: ['ऐ', 'ै'],
  au: ['औ', 'ौ'],
  ee: ['ई', 'ी'],
  ii: ['ई', 'ी'],
  oo: ['ऊ', 'ू'],
  uu: ['ऊ', 'ू'],
  a: ['अ', ''],
  i: ['इ', 'ि'],
  u: ['उ', 'ु'],
  e: ['ए', 'े'],
  o: ['ओ', 'ो'],
  A: ['आ', 'ा'],
  I: ['ई', 'ी'],
  U: ['ऊ', 'ू'],
  E: ['ए', 'े'],
  O: ['ओ', 'ो'],
}

export const DIGITS: Record<string, string> = {
  '0': '०',
  '1': '१',
  '2': '२',
  '3': '३',
  '4': '४',
  '5': '५',
  '6': '६',
  '7': '७',
  '8': '८',
  '9': '९',
}

export const SIGNS: Record<string, string> = {
  M: 'ं',
  H: 'ः',
  '~': 'ँ',
}
